#ifndef AUDIOTHREAD_GLOBAL_H
#define AUDIOTHREAD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AUDIOTHREAD_LIBRARY)
#  define AUDIOTHREADSHARED_EXPORT Q_DECL_EXPORT
#else
#  define AUDIOTHREADSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AUDIOTHREAD_GLOBAL_H
